<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Financial.Robot.Worker-db2fde8a-cd9b-462a-b5a9-2499c498dc9a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.17" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Skender.Stock.Indicators" Version="2.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financial.Robot.Application\Financial.Robot.Application.csproj" />
    <ProjectReference Include="..\Financial.Robot.Infrastructure\Financial.Robot.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MtApi5">
      <HintPath>..\..\libs\MtApi5.dll</HintPath>
    </Reference>
    <Reference Include="MtClient">
      <HintPath>..\..\libs\MtClient.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\config\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>config\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="logs\financial-robot-20260711.log" />
  </ItemGroup>
</Project>
